package com.longan.biz.dataobject;

import java.io.Serializable;
import java.util.Date;

import com.longan.biz.utils.BigDecimalUtils;
import com.longan.biz.utils.Constants;

public class AcctInfo implements Serializable {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Long id;

	private Long userId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.login_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private String loginId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.balance
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Long balance;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.last_trade_balance
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Long lastTradeBalance;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.gmt_create
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Date gmtCreate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.gmt_modify
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Date gmtModify;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.last_trade_date
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Date lastTradeDate;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.status
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Integer status;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.verification_code
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private String verificationCode;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_info.sales_price
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	private Integer salesPrice;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.id
	 * 
	 * @return the value of acct_info.id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.id
	 * 
	 * @param id
	 *            the value for acct_info.id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	public Long getUserId() {
		return userId;
	}

	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.login_id
	 * 
	 * @return the value of acct_info.login_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getLoginId() {
		return loginId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.login_id
	 * 
	 * @param loginId
	 *            the value for acct_info.login_id
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setLoginId(String loginId) {
		this.loginId = loginId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.balance
	 * 
	 * @return the value of acct_info.balance
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Long getBalance() {
		return balance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.balance
	 * 
	 * @param balance
	 *            the value for acct_info.balance
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setBalance(Long balance) {
		this.balance = balance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.last_trade_balance
	 * 
	 * @return the value of acct_info.last_trade_balance
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Long getLastTradeBalance() {
		return lastTradeBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.last_trade_balance
	 * 
	 * @param lastTradeBalance
	 *            the value for acct_info.last_trade_balance
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setLastTradeBalance(Long lastTradeBalance) {
		this.lastTradeBalance = lastTradeBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.gmt_create
	 * 
	 * @return the value of acct_info.gmt_create
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.gmt_create
	 * 
	 * @param gmtCreate
	 *            the value for acct_info.gmt_create
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.gmt_modify
	 * 
	 * @return the value of acct_info.gmt_modify
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Date getGmtModify() {
		return gmtModify;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.gmt_modify
	 * 
	 * @param gmtModify
	 *            the value for acct_info.gmt_modify
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.last_trade_date
	 * 
	 * @return the value of acct_info.last_trade_date
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Date getLastTradeDate() {
		return lastTradeDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.last_trade_date
	 * 
	 * @param lastTradeDate
	 *            the value for acct_info.last_trade_date
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setLastTradeDate(Date lastTradeDate) {
		this.lastTradeDate = lastTradeDate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.status
	 * 
	 * @return the value of acct_info.status
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.status
	 * 
	 * @param status
	 *            the value for acct_info.status
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.verification_code
	 * 
	 * @return the value of acct_info.verification_code
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public String getVerificationCode() {
		return verificationCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.verification_code
	 * 
	 * @param verificationCode
	 *            the value for acct_info.verification_code
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setVerificationCode(String verificationCode) {
		this.verificationCode = verificationCode;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_info.sales_price
	 * 
	 * @return the value of acct_info.sales_price
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public Integer getSalesPrice() {
		return salesPrice;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_info.sales_price
	 * 
	 * @param salesPrice
	 *            the value for acct_info.sales_price
	 * 
	 * @abatorgenerated Mon Feb 17 20:04:25 CST 2014
	 */
	public void setSalesPrice(Integer salesPrice) {
		this.salesPrice = salesPrice;
	}

	public String getBalanceDesc() {
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(balance));
		return result.toString();
	}

	public String getStatusDesc() {
		if (status == null) {
			return null;
		}
		if (Constants.AcctInfo.STATUS_NORMAL == status) {
			return Constants.AcctInfo.STATUS_NORMAL_DESC;
		} else if (Constants.AcctInfo.STATUS_FREEZE == status) {
			return Constants.AcctInfo.STATUS_FREEZE_DESC;
		} else if (Constants.AcctInfo.STATUS_DEL == status) {
			return Constants.AcctInfo.STATUS_DEL_DESC;
		}
		return null;
	}

	public String getSalePriceDesc() {
		if (salesPrice == null) {
			return null;
		}
		if (Constants.AcctInfo.SALES_PRICE_1 == salesPrice) {
			return Constants.AcctInfo.SALES_PRICE_1_DESC;
		} else if (Constants.AcctInfo.SALES_PRICE_2 == salesPrice) {
			return Constants.AcctInfo.SALES_PRICE_2_DESC;
		} else if (Constants.AcctInfo.SALES_PRICE_3 == salesPrice) {
			return Constants.AcctInfo.SALES_PRICE_3_DESC;
		} else if (Constants.AcctInfo.SALES_PRICE_4 == salesPrice) {
			return Constants.AcctInfo.SALES_PRICE_4_DESC;
		}
		return null;
	}
}