package com.longan.biz.dataobject;

import java.util.Date;

import com.longan.biz.utils.BigDecimalUtils;
import com.longan.biz.utils.Constants;

public class AcctLog {

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.id
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long id;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.gmt_create
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Date gmtCreate;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.gmt_modify
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Date gmtModify;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.user_id
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long userId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.acct_id
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long acctId;

	private Long billId;

	private Integer billType;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.biz_order_id
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long bizOrderId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.biz_id
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Integer bizId;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.status
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Integer status;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.trade_type
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Integer tradeType;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.amt_in
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long amtIn;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.amt_out
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long amtOut;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.amt_balance
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Long amtBalance;
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column acct_log.channel
	 * 
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	private Integer channel;

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.id
	 * 
	 * @return the value of acct_log.id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.id
	 * 
	 * @param id
	 *            the value for acct_log.id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.gmt_create
	 * 
	 * @return the value of acct_log.gmt_create
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Date getGmtCreate() {
		return gmtCreate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.gmt_create
	 * 
	 * @param gmtCreate
	 *            the value for acct_log.gmt_create
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setGmtCreate(Date gmtCreate) {
		this.gmtCreate = gmtCreate;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.gmt_modify
	 * 
	 * @return the value of acct_log.gmt_modify
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Date getGmtModify() {
		return gmtModify;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.gmt_modify
	 * 
	 * @param gmtModify
	 *            the value for acct_log.gmt_modify
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setGmtModify(Date gmtModify) {
		this.gmtModify = gmtModify;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.user_id
	 * 
	 * @return the value of acct_log.user_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.user_id
	 * 
	 * @param userId
	 *            the value for acct_log.user_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.acct_id
	 * 
	 * @return the value of acct_log.acct_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getAcctId() {
		return acctId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.acct_id
	 * 
	 * @param acctId
	 *            the value for acct_log.acct_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setAcctId(Long acctId) {
		this.acctId = acctId;
	}

	public Long getBillId() {
		return billId;
	}

	public void setBillId(Long billId) {
		this.billId = billId;
	}

	public Integer getBillType() {
		return billType;
	}

	public void setBillType(Integer billType) {
		this.billType = billType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.biz_order_id
	 * 
	 * @return the value of acct_log.biz_order_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getBizOrderId() {
		return bizOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.biz_order_id
	 * 
	 * @param bizOrderId
	 *            the value for acct_log.biz_order_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setBizOrderId(Long bizOrderId) {
		this.bizOrderId = bizOrderId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.biz_id
	 * 
	 * @return the value of acct_log.biz_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Integer getBizId() {
		return bizId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.biz_id
	 * 
	 * @param bizId
	 *            the value for acct_log.biz_id
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setBizId(Integer bizId) {
		this.bizId = bizId;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.status
	 * 
	 * @return the value of acct_log.status
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.status
	 * 
	 * @param status
	 *            the value for acct_log.status
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.trade_type
	 * 
	 * @return the value of acct_log.trade_type
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Integer getTradeType() {
		return tradeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.trade_type
	 * 
	 * @param tradeType
	 *            the value for acct_log.trade_type
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setTradeType(Integer tradeType) {
		this.tradeType = tradeType;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.amt_in
	 * 
	 * @return the value of acct_log.amt_in
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getAmtIn() {
		return amtIn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.amt_in
	 * 
	 * @param amtIn
	 *            the value for acct_log.amt_in
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setAmtIn(Long amtIn) {
		this.amtIn = amtIn;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.amt_out
	 * 
	 * @return the value of acct_log.amt_out
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getAmtOut() {
		return amtOut;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.amt_out
	 * 
	 * @param amtOut
	 *            the value for acct_log.amt_out
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setAmtOut(Long amtOut) {
		this.amtOut = amtOut;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.amt_balance
	 * 
	 * @return the value of acct_log.amt_balance
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Long getAmtBalance() {
		return amtBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.amt_balance
	 * 
	 * @param amtBalance
	 *            the value for acct_log.amt_balance
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setAmtBalance(Long amtBalance) {
		this.amtBalance = amtBalance;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column acct_log.channel
	 * 
	 * @return the value of acct_log.channel
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public Integer getChannel() {
		return channel;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column acct_log.channel
	 * 
	 * @param channel
	 *            the value for acct_log.channel
	 * @abatorgenerated Sun Feb 23 20:04:48 CST 2014
	 */
	public void setChannel(Integer channel) {
		this.channel = channel;
	}

	public String getAmtInDesc() {
		if (amtIn == null) {
			return null;
		}
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(amtIn));
		return result.toString();
	}

	public String getAmtOutDesc() {
		if (amtOut == null) {
			return null;
		}
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(amtOut));
		return result.toString();
	}

	public String getAmtBalanceDesc() {
		if (amtBalance == null) {
			return null;
		}
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(amtBalance));
		return result.toString();
	}

	public boolean showRed() {
		if (status == null) {
			return false;
		}
		return Constants.AcctLog.STATUS_EXCEPTION == status;
	}

	public boolean showGreen() {
		if (status == null) {
			return false;
		}
		return Constants.AcctLog.STATUS_NORMAL == status;
	}

	public String getStatusDesc() {
		String result = null;
		if (status == null) {
			return null;
		}
		if (Constants.AcctLog.STATUS_EXCEPTION == status) {
			result = Constants.AcctLog.STATUS_EXCEPTION_DESC;
		} else if (Constants.AcctLog.STATUS_NORMAL == status) {
			result = Constants.AcctLog.STATUS_NORMAL_DESC;
		}
		return result;
	}

	public String getTradeTypeDesc() {
		String result = null;
		if (tradeType == null) {
			return null;
		}
		if (Constants.AcctLog.TRADE_TYPE_IN == tradeType) {
			result = Constants.AcctLog.TRADE_TYPE_IN_DESC;
		} else if (Constants.AcctLog.TRADE_TYPE_OUT == tradeType) {
			result = Constants.AcctLog.TRADE_TYPE_OUT_DESC;
		}
		return result;
	}

	public String getBillTypeDesc() {
		String result = null;
		if (billType == null) {
			return null;
		}
		if (Constants.AcctLog.BILL_TYPE_CHARGE_ORDER == billType) {
			result = Constants.AcctLog.BILL_TYPE_CHARGE_ORDER_DESC;
		} else if (Constants.AcctLog.BILL_TYPE_PAY_ORDER == billType) {
			result = Constants.AcctLog.BILL_TYPE_PAY_ORDER_DESC;
		} else if (Constants.AcctLog.BILL_TYPE_REFUND_ORDER == billType) {
			result = Constants.AcctLog.BILL_TYPE_REFUND_ORDER_DESC;
		} else if (Constants.AcctLog.BILL_TYPE_CASH_ORDER == billType) {
			result = Constants.AcctLog.BILL_TYPE_CASH_ORDER_DESC;
		}
		return result;
	}

	private String itemId;
	private String itemName;
	private String upStreamId;

	public String getItemId() {
		return itemId;
	}

	public void setItemId(String itemId) {
		this.itemId = itemId;
	}

	public String getItemName() {
		return itemName;
	}

	public void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public String getUpStreamId() {
		return upStreamId;
	}

	public void setUpStreamId(String upStreamId) {
		this.upStreamId = upStreamId;
	}

	public double getAmtInDouble() {
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(amtIn));
		return result;
	}

	public double getAmtOutDouble() {
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(amtOut));
		return result;
	}

	public double getAmtBalanceDouble() {
		Double result = BigDecimalUtils.doubleDiveid(String.valueOf(amtBalance));
		return result;
	}
}